name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Create virtual environment
      run: python -m venv venv

    - name: Activate virtual environment and install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -e .

    - name: Run Tests
      run: |
        source venv/bin/activate
        pytest --cov=tutor_stack_assessment --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        file: ./coverage.xml
        flags: assessment
        name: assessment-coverage

  lint:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Create virtual environment
      run: python -m venv venv

    - name: Activate virtual environment and install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run black
      run: |
        source venv/bin/activate
        black --check tutor_stack_assessment tests

    - name: Run isort
      run: |
        source venv/bin/activate
        isort --check-only tutor_stack_assessment tests

    - name: Run flake8
      run: |
        source venv/bin/activate
        flake8 tutor_stack_assessment tests

    - name: Run mypy
      run: |
        source venv/bin/activate
        mypy tutor_stack_assessment tests

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: assessment-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max 